# Generated by Django 5.1.1 on 2024-10-03 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
