# Generated by Django 5.1.1 on 2024-10-04 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_joblisting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joblisting',
            old_name='comapny',
            new_name='company',
        ),
    ]
